version: '3.1'

services:
  api:
    build: .
    env_file: .env
    depends_on:
      - db
    command: npm test --watchAll
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: calluhelp
      MYSQL_LOG_CONSOLE: "true"
