version: '3.1'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: calluhelp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
